server:
  port: 8081

spring:
  application:
    name: fraud


  datasource:
    username: 'amigoscode'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/fraud

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

        jdbc:
          lob:
            non_contextual_creation: true
